Elpy\Bundle\GeneralBundle\Entity\Module:
    type: entity
    table: null
    repositoryClass: Elpy\Bundle\GeneralBundle\Entity\ModuleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
