knowledgetype:
    path:     /
    defaults: { _controller: "ElpyGeneralBundle:KnowledgeType:index" }

knowledgetype_show:
    path:     /{id}/show
    defaults: { _controller: "ElpyGeneralBundle:KnowledgeType:show" }

knowledgetype_new:
    path:     /new
    defaults: { _controller: "ElpyGeneralBundle:KnowledgeType:new" }

knowledgetype_create:
    path:     /create
    defaults: { _controller: "ElpyGeneralBundle:KnowledgeType:create" }
    methods:  POST

knowledgetype_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElpyGeneralBundle:KnowledgeType:edit" }

knowledgetype_update:
    path:     /{id}/update
    defaults: { _controller: "ElpyGeneralBundle:KnowledgeType:update" }
    methods:  [POST, PUT]

knowledgetype_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElpyGeneralBundle:KnowledgeType:delete" }
    methods:  [POST, DELETE]
